language: node_js
node_js:
  - 10

script:
  - yarn install
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git config user.name "pengcu"
  - git config user.email "pengcumail@gmail.com"
  - git add .
  - git commit -am "ğŸ‘·ğŸ»â€ Auto Builder"
  - git push --force --quiet "https://${GITHUB_API_KEY}@github.com/pengcu/three-go.git" gh-pages

branches:
  only:
  - master